### ISSUE TITLE
Shindou edition does not compile, but others do

### ISSUE THREAD

**Issue by AgentCichy** [martepato/sm64-vita#4]
thread6.c:(.text+0x468): undefined reference to `osStartThread'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:863: build/sh_vita/sm64.sh.f3dex2e] Error 1

**Comment by martepato** [comment]
While I am not certain that Shindou was compiling nicely along the others before merging changes from upstream, I am able to successfully compile Shindou edition. Let me know if you can build it too.

For reference: https://github.com/martepato/sm64-vita/commit/ee4ff4f6ee39d6694f5c678fb9593e3a197e259c
